### PR TITLE
✨  Clean build folder and use build path from webpack.config.js

### PR DESCRIPTION
**Pull request by markov00**
This fix will clean the build folder before compilation and allows to change the build path on your local `webpack.config.js` file

### CODE REVIEW

**Comment by caesarsol** [comment]
👍 !

**Comment by marcofugaro** [comment]
👮 Ehi ehi @markov00 I am seeing some compiled files in the repo, what is the folder `test_build/` for?

Did you know about the [`yarn create-test-app` script](https://github.com/accurat/accurapp/blob/master/package.json#L12)?

**Comment by markov00** [comment]
Sorry for that @marcofugaro, strange that I also commited these files.
I knows about `create-test-app` but from @caesarsol not from the repo itself. Maybe adding this to the `README.md` file can help in a better contribution

**Comment by marcofugaro** [comment]
👌 💯

**Pull request merged**
